name: Model-training-evaluation
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-dvc@v1
      - name: create .databrickscfg
        run: |
          echo "${{ secrets.DATABRICKS_CFG }}" > ~/.databrickscfg
      - name: Train model
        env:
          GDRIVE_CREDENTIALS_DATA: ${{secrets.GDRIVE_CREDENTIALS_DATA}}
        run: |
          pip install -r requirements.txt   # Install dependencies
          dvc pull data/data.csv                 # Pull data
          dvc repro                         # Reproduce pipeline

      - name: Create CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics:" >> report.md
          
          git config --global --add safe.directory /__w/credit-classification/credit-classification
          git fetch --prune
          echo metrics.json >> report.md
          dvc metrics diff master --md > report.md
          echo '![](./feature_importance.png "Feature Importance")' >> report.md
          cml comment create report.md
