name: Model-training-evaluation
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-dvc@v1
      - name: Train model
        env:
          GDRIVE_CREDENTIALS_DATA: ${{secrets.GDRIVE_CREDENTIALS_DATA}}
        run: |
          pip install -r requirements.txt   # Install dependencies
          dvc pull data/data.csv                 # Pull data
          dvc repro                         # Reproduce pipeline

      - name: Create CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --depth=1 origin main:main
          dvc metrics diff master --show-md >> report.md
          cat metrics.json
          cat metrics.json >> report.md
          echo '![](./feature_importance.png "Feature Importance")' >> report.md
          cml comment create report.md
