name: Model-training-evaluation
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
  
        run: |
          pip install -r requirements.txt   # Install dependencies
          dvc repro                         # Reproduce pipeline

      - name: Create CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat metrics.json
          cat metrics.json >> report.md
          echo '![](./feature_importance.png "Feature Importance")' >> report.md
          cml comment create report.md